In [1]:
1+1

2

# dataviz_pronos_complet.ipynb

Importations

In [2]:
import sqlite3
import pandas as pd

In [3]:
import matplotlib.pyplot as plt
import seaborn as sns

Connexion à la db

In [4]:
import os
os.listdir()

['.ipynb_checkpoints', 'dataviz_pronos.ipynb', 'guide.ipynb']

In [5]:
import os

for root, dirs, files in os.walk("C:\\"):
    if "db.sqlite3" in files:
        print(os.path.join(root, "db.sqlite3"))

C:\Users\xavie\Documents\Rugby_app\backend\db.sqlite3
C:\Users\xavie\Documents\Rugby_app\backend\core\db.sqlite3
C:\Users\xavie\Downloads\db.sqlite3

In [6]:
import sqlite3
import pandas as pd

db1 = r"C:\Users\xavie\Documents\Rugby_app\backend\db.sqlite3"
conn1 = sqlite3.connect(db1)

tables1 = pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn1
)

tables1

                          name
0            django_migrations
1              sqlite_sequence
2       auth_group_permissions
3             auth_user_groups
4   auth_user_user_permissions
5             django_admin_log
6          django_content_type
7              auth_permission
8                   auth_group
9                    auth_user
10            core_competition
11                  core_match
12                 core_player
13       core_competitionbonus
14             core_prediction
15                  core_round
16             core_dailybonus
17          core_scoringconfig
18                   core_team
19      core_team_competitions
20             core_dailyscore
21            core_seasonscore
22              django_session

Lecture des tables principales

In [7]:
cursor = conn1.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()
print(tables)

[('django_migrations',), ('sqlite_sequence',), ('auth_group_permissions',), ('auth_user_groups',), ('auth_user_user_permissions',), ('django_admin_log',), ('django_content_type',), ('auth_permission',), ('auth_group',), ('auth_user',), ('core_competition',), ('core_match',), ('core_player',), ('core_competitionbonus',), ('core_prediction',), ('core_round',), ('core_dailybonus',), ('core_scoringconfig',), ('core_team',), ('core_team_competitions',), ('core_dailyscore',), ('core_seasonscore',), ('django_session',)]

In [8]:
players = pd.read_sql("SELECT * FROM core_player", conn1)
players

Empty DataFrame
Columns: [id, name, user_id]
Index: []

In [9]:
competitions = pd.read_sql("SELECT * FROM core_competition", conn1)
competitions

Empty DataFrame
Columns: [id, name, season, bonus_defense_threshold, match_weight]
Index: []

In [10]:
teams = pd.read_sql("SELECT * FROM core_team", conn1)
teams

Empty DataFrame
Columns: [id, name]
Index: []

In [11]:
tables = pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'core_%';",
    conn1
)

counts = []

for table in tables["name"]:
    count = pd.read_sql(
        f"SELECT COUNT(*) AS n FROM {table};",
        conn1
    )["n"][0]
    counts.append({"table": table, "rows": count})

pd.DataFrame(counts).sort_values("rows", ascending=False)

                     table  rows
0         core_competition     0
1               core_match     0
2              core_player     0
3    core_competitionbonus     0
4          core_prediction     0
5               core_round     0
6          core_dailybonus     0
7       core_scoringconfig     0
8                core_team     0
9   core_team_competitions     0
10         core_dailyscore     0
11        core_seasonscore     0

In [12]:
pd.read_sql("SELECT * FROM core_competition LIMIT 10;", conn1)

Empty DataFrame
Columns: [id, name, season, bonus_defense_threshold, match_weight]
Index: []

### Téléchargement de la db depuis PythonAnywhere dans Dashboard/files puis ouverture de la db

In [13]:
db_telechargee = r"C:\Users\xavie\Downloads\db.sqlite3"
conn_dl = sqlite3.connect(db_telechargee)

tables_dl = pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn_dl
)

tables_dl

                                 name
0                   django_migrations
1                     sqlite_sequence
2              auth_group_permissions
3                    auth_user_groups
4          auth_user_user_permissions
5                    django_admin_log
6                 django_content_type
7                     auth_permission
8                          auth_group
9                           auth_user
10                         core_match
11                        core_player
12              core_competitionbonus
13                    core_prediction
14                    core_dailybonus
15                 core_scoringconfig
16                          core_team
17             core_team_competitions
18                    core_dailyscore
19                   core_seasonscore
20                     django_session
21                         core_round
22                   core_competition
23                        core_season
24  core_competitionrankingprediction
25         core_teamrankingprediction
26    core_competitionbonusprediction
27     core_competitionteamprediction
28               core_competitionteam

In [14]:
tables = pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'core_%';",
    conn_dl
)

counts = []

for table in tables["name"]:
    count = pd.read_sql(
        f"SELECT COUNT(*) AS n FROM {table};",
        conn_dl
    )["n"][0]
    counts.append({"table": table, "rows": count})

pd.DataFrame(counts).sort_values("rows", ascending=False)

                                table  rows
7              core_team_competitions    44
14         core_teamrankingprediction    43
6                           core_team    36
17               core_competitionteam    24
3                     core_prediction    20
0                          core_match    20
10                         core_round     4
15    core_competitionbonusprediction     3
11                   core_competition     3
13  core_competitionrankingprediction     3
12                        core_season     3
1                         core_player     1
9                    core_seasonscore     0
5                  core_scoringconfig     0
2               core_competitionbonus     0
8                     core_dailyscore     0
4                     core_dailybonus     0
16     core_competitionteamprediction     0

In [27]:
df_core_competition = pd.read_sql("SELECT * FROM core_competition;", conn_dl)
df_core_competition.head()

,id,name,bonus_defense_threshold,match_weight,matches_per_round
0,1,Top 14,5,680,7
1,2,Tournoi des 6 Nations,7,680,3
2,3,Champions Cup,7,680,12

In [16]:
df_core_team_competition = pd.read_sql("SELECT * FROM core_team_competitions LIMIT10;", conn_dl)
df_core_team_competition.head()

   id  team_id  competition_id
0   1        1               1
1   2        2               1
2   3        3               1
3   4        4               1
4   5        5               1

In [17]:
df_core_teamrankingprediction = pd.read_sql("SELECT * FROM core_teamrankingprediction LIMIT10;", conn_dl)
df_core_teamrankingprediction.head()

   id  position  pool  ranking_id  team_id
0   1         1  None           1        1
1   2         2  None           1        2
2   3         3  None           1        3
3   4         4  None           1        4
4   5         5  None           1        5

In [18]:
df_core_team = pd.read_sql("SELECT * FROM core_team LIMIT10;", conn_dl)
df_core_team.head()

   id         name
0   1       Toulon
1   2     Toulouse
2   3  Montpellier
3   4         Lyon
4   5     Clermont

In [19]:
df_core_competitionteam = pd.read_sql("SELECT * FROM core_competitionteam LIMIT10;", conn_dl)
df_core_competitionteam.head()

   id  pool  competition_id  season_id  team_id
0   1     2               3          3        1
1   2     1               3          3        2
2   3     1               3          3        5
3   4     2               3          3        7
4   5     4               3          3        9

In [20]:
df_core_prediction = pd.read_sql("SELECT * FROM core_prediction LIMIT10;", conn_dl)
df_core_prediction.head()

,id,home_score_pred,away_score_pred,bonus_home_pred,bonus_away_pred,points,match_id,player_id
0,1,22,15,0,0,0,7,1
1,2,12,12,0,0,0,13,1
2,3,65,12,1,0,0,17,1
3,4,12,15,0,0,0,16,1
4,5,15,35,0,0,0,3,1

In [43]:
df_match_pred_join = pd.read_sql("SELECT * FROM core_prediction cpr JOIN core_player cpl ON cpl.id = cpr.player_id;", conn_dl)
df_match_pred_join.head(2)

,id,home_score_pred,away_score_pred,bonus_home_pred,bonus_away_pred,points,match_id,player_id,id,name,user_id
0,1,22,15,0,0,0,7,1,1,Xavier,2
1,2,12,12,0,0,0,13,1,1,Xavier,2

In [45]:
df_match_pred_join_join = pd.read_sql("SELECT * FROM core_prediction cpr JOIN core_player cpl ON cpl.id = cpr.player_id JOIN core_match cm ON cm.id = cpr.match_id;", conn_dl)
df_match_pred_join_join.head(2)

,id,home_score_pred,away_score_pred,bonus_home_pred,bonus_away_pred,points,match_id,player_id,id,name,...,phase,bonus_offense_home,bonus_offense_away,bonus_defense_home,bonus_defense_away,round_id,away_team_id,home_team_id,kickoff_at,match_datetime
0,1,22,15,0,0,0,7,1,1,Xavier,...,POOL,0,0,0,0,3,13,9,2026-01-24 14:30:00,None
1,2,12,12,0,0,0,13,1,1,Xavier,...,POOL,0,0,0,0,5,19,17,2026-02-14 15:10:00,None

In [ ]:
df_match_pred_join_join_join = pd.read_sql("SELECT * FROM core_prediction cpr JOIN core_player cpl ON cpl.id = cpr.player_id JOIN core_match cm ON cm.id = cpr.match_id ;", conn_dl)
df_match_pred_join_join_join.head(2)

In [21]:
df_core_match = pd.read_sql("SELECT * FROM core_match LIMIT10;", conn_dl)
df_core_match.head()

,id,home_score,away_score,weight,phase,bonus_offense_home,bonus_offense_away,bonus_defense_home,bonus_defense_away,round_id,away_team_id,home_team_id,kickoff_at,match_datetime
0,1,None,None,680,POOL,0,0,0,0,3,10,5,2026-01-25 21:05:00,None
1,2,None,None,680,POOL,0,0,0,0,3,11,2,2026-01-24 21:00:00,None
2,3,None,None,680,POOL,0,0,0,0,3,3,1,2026-01-24 16:35:00,None
3,4,None,None,680,POOL,0,0,0,0,3,4,14,2026-01-24 16:35:00,None
4,5,None,None,680,POOL,0,0,0,0,3,7,12,2026-01-24 16:35:00,None

In [22]:
df_core_player = pd.read_sql("SELECT * FROM core_player LIMIT10;", conn_dl)
df_core_player.head()

   id    name  user_id
0   1  Xavier        2

In [23]:
df_core_round = pd.read_sql("SELECT * FROM core_round LIMIT10;", conn_dl)
df_core_round.head()

   id  number        date  season_id
0   3      15  2026-01-24          1
1   4       1  2026-02-07          2
2   5       2  2026-02-14          2
3   6      16  2026-01-31          1

In [24]:
df_core_season = pd.read_sql("SELECT * FROM core_season LIMIT10;", conn_dl)
df_core_season.head()

   id  competition_id       year
0   1               1  2025/2026
1   2               2       2026
2   3               3  2025/2026

In [25]:
df_core_competitionrankingprediction = pd.read_sql("SELECT * FROM core_competitionrankingprediction LIMIT10;", conn_dl)
df_core_competitionrankingprediction.head()

,id,best_try_scorer,best_kicker,locked_at,competition_id,player_id,season_id,winner_team_id
0,1,,,None,1,1,1,None
1,2,,,None,2,1,2,None
2,3,,,None,3,1,3,None

In [26]:
df_core_competitionbonusprediction = pd.read_sql("SELECT * FROM core_competitionbonusprediction LIMIT10;", conn_dl)
df_core_competitionbonusprediction.head()

   id best_point_scorer  competition_id  player_id best_try_scorer
0   1                 1               1          1               1
1   2                                 2          1           Dréan
2   3                                 3          1

In [41]:
pd.read_sql("SELECT * FROM core_team_competitions AS ctc JOIN core_competition AS cc ON cc.id = ctc.competition_id JOIN core_team AS ct ON ct.id = ctc.team_id;", conn_dl).head()

,id,team_id,competition_id,id,name,bonus_defense_threshold,match_weight,matches_per_round,id,name
0,1,1,1,1,Top 14,5,680,7,1,Toulon
1,2,2,1,1,Top 14,5,680,7,2,Toulouse
2,3,3,1,1,Top 14,5,680,7,3,Montpellier
3,4,4,1,1,Top 14,5,680,7,4,Lyon
4,5,5,1,1,Top 14,5,680,7,5,Clermont